baseURL = 'https://dwango.github.io/nicolive-kubernetes-migration-handbook-2022'
languageCode = 'ja-JP'
title = 'ニコニコ生放送 Webフロントエンド Kubernetes移行ハンドブック 2022'
theme = "hugo-book"

googleAnalytics = "G-2W6W35K13D"

disablePathToLower = true
enableGitInfo = true

[params]
  BookTheme = 'auto'
  BookToC = true
  BookServiceWorker = true
  BookRepo = "https://github.com/dwango/nicolive-kubernetes-migration-handbook-2022"
  BookEditPath = "edit/main"

[markup]
[markup.goldmark.renderer]
  unsafe = true
