baseURL = 'https://dwango.github.io/nicolive-kubernetes-migration-handbook-2022'
languageCode = 'ja-JP'
theme = "hugo-book"
title = 'ニコニコ生放送 Webフロントエンド Kubernetes移行ハンドブック 2022'

googleAnalytics = "G-2W6W35K13D"

disablePathToLower = true
enableGitInfo = true

[params]
BookEditPath = "edit/main"
BookRepo = "https://github.com/dwango/nicolive-kubernetes-migration-handbook-2022"
BookSearch = false
BookServiceWorker = true
BookTheme = 'auto'
BookToC = true
description = 'ニコニコ生放送 on Kubernetes'
images = ['site-feature-image.png']

[markup]
[markup.goldmark.renderer]
unsafe = true
